"""
LANG: The language of the application.
"""
LANG = {
    "Splash screen displayed for": "Splash screen displayed for",
    "took": "took",
    "seconds": "seconds",
    "milliseconds": "milliseconds",
    "PHP ini file renamed successfully from": "PHP ini file renamed successfully from",
    "to": "to",
    "PHP ini stub file content read successfully from": "PHP ini stub file content read successfully from",
    "PHP ini file updated successfully with the new variables": "PHP ini file updated successfully with the new variables",
    "Downloading PHP from": "Downloading PHP from",
    "PHP downloaded successfully": "PHP downloaded successfully",
    "PHP unzipped successfully": "PHP unzipped successfully",
    "PHP ZIP file deleted successfully": "PHP ZIP file deleted successfully",
    "Error downloading PHP because of:": "Error downloading PHP because of:",
    "PHP version not found or unsupported for your platform": "PHP version not found or unsupported for your platform",
    "PHP executable not found so it will be downloaded automatically": "PHP executable not found so it will be downloaded automatically",
    "PHP executable was not found. Do you want to install PHP automatically?": "PHP executable was not found. Do you want to install PHP automatically?",
    "PHP Not Found": "PHP Not Found",
    "User response:": "User response:",
    "User selected to install PHP automatically": "User selected to install PHP automatically",
    "User bitNess:": "User bitNess:",
    "64bit detected so we will download the 64bit version of PHP": "64bit detected so we will download the 64bit version of PHP",
    "32bit detected so we will download the 32bit version of PHP": "32bit detected so we will download the 32bit version of PHP",
    "Select an option:": "Select an option:",
    "Select PHP version to download": "Select PHP version to download",
    "User selected option:": "User selected option:",
    "User cancelled the installation of PHP": "User cancelled the installation of PHP",
    "Laravel root and public folders not found so we will redirect to the": "Laravel root and public folders not found so we will redirect to the",
    "file": "file",
    "Error starting PHP server:": "Error starting PHP server:",
    "PHP server started at": "PHP server started at",
    "in": "in",
    "PHP server stopped at": "PHP server stopped at",
    "Error starting application:": "Error starting application:",
    "PHP CGI process found so we will kill it": "PHP CGI process found so we will kill it",
    "PHP CGI process killed successfully": "PHP CGI process killed successfully",
    "PHP CGI process not found": "PHP CGI process not found",
    "Application closed successfully by the user": "Application closed successfully by the user",
    "Are you sure you want to exit?": "Are you sure you want to exit?",
    "Exit Application": "Exit Application",
    "Application close cancelled by the user": "Application close cancelled by the user",
    "Composer downloaded successfully": "Composer downloaded successfully",
    "Laravel project created successfully": "Laravel project created successfully",
    "Vendor downloaded successfully": "Vendor downloaded successfully",
    "Key generated successfully": "Key generated successfully",
    "Laravel project already exists": "Laravel project already exists",
    "Creating Laravel project in": "Creating Laravel project in",
    "Currently there is no Laravel project in the current directory, we will ask the user to create one": "Currently there is no Laravel project in the current directory, we will ask the user to create one",
    "Current directory does not contain a Laravel project. Do you want to create one?": "Current directory does not contain a Laravel project. Do you want to create one?",
    "Laravel Project Not Found": "Laravel Project Not Found",
    "User cancelled the creation of Laravel project": "User cancelled the creation of Laravel project",
    "Composer file downloaded successfully": "Composer file downloaded successfully",
    "Composer setup file executed successfully": "Composer setup file executed successfully",
    "Composer setup file deleted successfully": "Composer setup file deleted successfully",
    "Laravel project moved successfully to the Laravel project directory": "Laravel project moved successfully to the Laravel project directory",
    "Error creating Laravel project because of:": "Error creating Laravel project because of:",
    "Laravel project downloaded successfully in": "Laravel project downloaded successfully in",
    "Laravel project created successfully in": "Laravel project created successfully in",
    "Composer phar file already exists in the Laravel project directory": "Composer phar file already exists in the Laravel project directory",
    "Error displaying splash screen because of:": "Error displaying splash screen because of:",
    "Internet connection detected successfully": "Internet connection detected successfully",
    "Internet connection not detected. Please check your internet connection and try again": "Internet connection not detected. Please check your internet connection and try again",
    "Internet Connection Error": "Internet Connection Error",
    "Key not found:": "Key not found:",
    "Error killing PHP CGI process:": "Error killing PHP CGI process:",
    "Composer phar file moved successfully to the Laravel project directory": "Composer phar file moved successfully to the Laravel project directory",
    "Env file not found": "Env file not found",
    "Environment file not found": "Environment file not found",
    ".env file renamed successfully": ".env file renamed successfully",
}
